In [2]:
#importing
import numpy as np

In [ ]:
#creating 1D array
A = np.array([2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#craeting 2D array #rows and coloumns
B=np.array([[2,3,4],[7,8,9]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
#creating 3D array- rowa,columns,groups
C=np.array([[[1,2,3],[4,5,6]],[[1,3,5],[2,4,6]]])
print(C)

[[[1 2 3]
  [4 5 6]]

 [[1 3 5]
  [2 4 6]]]


In [ ]:
#checking dimensions
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
#ones
D = np.ones((3,2)) #rows ,columns,2D
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#eye
J=np.eye(4)
print(J)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
R=np.eye(4,3)
print(R)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [7]:
#Zeros
E=np.zeros(3)
print(E)

[0. 0. 0.]


In [ ]:
#arange
H=np.arange(3,31,4)  #start,stop,step
print(H)

[ 3  7 11 15 19 23 27]


In [ ]:
N=np.arange(3,31,3).reshape(5,2)
print(N)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
#5 table upto 1000
K=np.arange(5,1001,5).reshape(10,20)
print(K)

[[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
    75   80   85   90   95  100]
 [ 105  110  115  120  125  130  135  140  145  150  155  160  165  170
   175  180  185  190  195  200]
 [ 205  210  215  220  225  230  235  240  245  250  255  260  265  270
   275  280  285  290  295  300]
 [ 305  310  315  320  325  330  335  340  345  350  355  360  365  370
   375  380  385  390  395  400]
 [ 405  410  415  420  425  430  435  440  445  450  455  460  465  470
   475  480  485  490  495  500]
 [ 505  510  515  520  525  530  535  540  545  550  555  560  565  570
   575  580  585  590  595  600]
 [ 605  610  615  620  625  630  635  640  645  650  655  660  665  670
   675  680  685  690  695  700]
 [ 705  710  715  720  725  730  735  740  745  750  755  760  765  770
   775  780  785  790  795  800]
 [ 805  810  815  820  825  830  835  840  845  850  855  860  865  870
   875  880  885  890  895  900]
 [ 905  910  915  920  925  930  935  940  945  950  95

In [ ]:
#linspace
W=np.linspace(12,24,11)
print(W)

[12.  13.2 14.4 15.6 16.8 18.  19.2 20.4 21.6 22.8 24. ]


In [ ]:
X=np.linspace(12,24,3)
print(X)

[12. 18. 24.]


In [10]:
K=np.arange(1,7).reshape(2,3)
print(K)
L=np.arange(9,15).reshape(2,3)
print(L)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [11]:
print(K+L)

[[10 12 14]
 [16 18 20]]


In [12]:
S=np.sum(K)
print(S)

21


In [ ]:
F=np.sum((K,L),axis=0) #column wise addition
print(F)

[[10 12 14]
 [16 18 20]]


In [ ]:
F=np.sum((K,L),axis=1) #row wise addition
print(F)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
F=np.sum((K,L),axis=2) #group wise addition
print(F)

[[ 6 15]
 [30 39]]


In [ ]:
  #example
  O=np.ones((4,2))
  N=np.ones((4,2))
  p=np.sum((O,N),axis=0)
  print(p)


[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
p=np.sum((O,N),axis=1)
print(p)

[[4. 4.]
 [4. 4.]]


In [ ]:
#multiplication of arrays
Q=np.array([[1,1],[0,1]])
R=np.array([[2,0],[3,4]])
S=Q*R
print(S)

[[2 0]
 [0 4]]


b=np.array(25,289,361,81) find square root and iterate through result values

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  c=np.sqrt(i)
  print(c,"square is",i)

5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


In [ ]:
u=np.array([25,81])
t=np.sqrt(u)
x=zip(u,t)
x=list(x)
print(x)


[(25, 5.0), (81, 9.0)]


In [14]:
a=np.array([34,35,36,37,38,39]).reshape(2,3)
print(a,"\n")
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(b,"\n")
print(np.vstack((a,b))) #columns
print("\n")
print(np.hstack((a,b))) #rows

[[34 35 36]
 [37 38 39]] 

[[4 5 6]
 [7 8 9]] 

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a,"\n output:")
print(np.dstack(a))
#no of rows become no of groups
#columns become rows
#group become columns

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
 output:
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
