In [ ]:
import numpy as np
#random is subpackage of numpy

to use subpackage we should follow syntax: <package_name>.<subpackage>(rows,columns)

In [ ]:
A=np.random.rand(8,4) #rand => range is between 0 and 1
print(A)

[[0.01108836 0.50944277 0.02669969 0.59489778]
 [0.39491696 0.59638381 0.27573075 0.61873908]
 [0.5435073  0.85847202 0.72635634 0.48266992]
 [0.56545605 0.77005261 0.14302198 0.9379002 ]
 [0.00870678 0.47637229 0.17617159 0.27314086]
 [0.52190685 0.40395997 0.53753739 0.88523612]
 [0.3928491  0.07516602 0.62505206 0.35377377]
 [0.69220384 0.82219703 0.78883708 0.9498028 ]]


In [ ]:
B=10*np.random.rand(8,4)
print(B)

[[8.6406562  8.76159257 6.96824496 6.67473694]
 [8.25109783 3.46268207 5.5310937  4.62704693]
 [1.9626851  5.16642698 1.75070373 6.04263827]
 [4.57708012 4.15990939 9.69689477 0.03272899]
 [2.43685604 2.62298264 5.20119798 5.93482416]
 [1.30468837 9.74678851 2.01074204 3.61297367]
 [7.66473026 7.60919487 9.93601746 4.61624084]
 [5.45094178 7.07166251 4.39614671 8.85378241]]


In [ ]:
C=np.floor(10*np.random.rand(8,4))
print(C)

[[6. 5. 3. 1.]
 [8. 1. 1. 6.]
 [2. 7. 7. 1.]
 [5. 5. 6. 8.]
 [2. 3. 3. 8.]
 [1. 5. 6. 9.]
 [9. 5. 2. 4.]
 [7. 1. 7. 1.]]


In [ ]:
D=np.arange(1,33).reshape(8,4)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(D,8)


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]]),
 array([[21, 22, 23, 24]]),
 array([[25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [ ]:
np.vsplit(D,(3,5)) #split it after 3rd and 5th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
#create an 4r and 8c
E=np.arange(1,33).reshape(4,8)
print(E)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(E,(np.arange(1,9))) #hsplit =>np.hsplit(E,(2,3))=> split at column 2 and 3

[array([[ 1],
        [ 9],
        [17],
        [25]]),
 array([[ 2],
        [10],
        [18],
        [26]]),
 array([[ 3],
        [11],
        [19],
        [27]]),
 array([[ 4],
        [12],
        [20],
        [28]]),
 array([[ 5],
        [13],
        [21],
        [29]]),
 array([[ 6],
        [14],
        [22],
        [30]]),
 array([[ 7],
        [15],
        [23],
        [31]]),
 array([[ 8],
        [16],
        [24],
        [32]]),
 array([], shape=(4, 0), dtype=int64)]

In [ ]:
#trignometry
np.pi

3.141592653589793

In [ ]:
l=[2,3,4,4,5,6,7,7,7,7]
np.mean(l)

5.2

In [ ]:
import numpy as np
F=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(F)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
import numpy as np
G=np.rad2deg(F)
print(G)   #rad2deg used to convert radians to degree

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(G)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(np.pi/4)
print(1/(2**0.5))

0.7071067811865475


In [ ]:
H=np.array([2,3,4,5,6,9,9,55,7,8])
np.mean(H)

10.8

In [ ]:
np.median(H)

6.5

In [ ]:
np.std(H) #std=sqrt(sigma(xi-xbar)^2 / n)

14.911740341086952

In [ ]:
np.var(H)    #var=std^2

222.36000000000004

In [ ]:
I=np.arange(1,5).reshape(2,2)
print(I)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(I)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
J=np.arange(1,25).reshape(6,4)
print(J)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(J))

23


In [ ]:
K=np.random.rand(6,4)
print(K)

[[0.48309228 0.69868254 0.31477122 0.01723487]
 [0.27254845 0.62753854 0.52791594 0.88323476]
 [0.6527679  0.63560833 0.72994001 0.2575289 ]
 [0.69253005 0.87553874 0.42244868 0.35602363]
 [0.93871522 0.73100184 0.05038372 0.95788942]
 [0.81558581 0.27292395 0.26118064 0.59946824]]


In [ ]:
print(np.argmax(K))  #argmax subpackage gives position of large element in given array

19


In [ ]:
print(np.argmax(K,axis=0))

[4 3 2 4]


In [ ]:
print(np.argmax(K,axis=1))

[1 3 2 1 3 0]


In [ ]:
L=np.random.rand(1,6,4)
print(L)

[[[0.57753649 0.9071925  0.53183523 0.12441576]
  [0.6748676  0.30698994 0.85101527 0.83148347]
  [0.06033721 0.35945859 0.16467867 0.14329456]
  [0.14362148 0.12142109 0.99418027 0.26637   ]
  [0.92670611 0.83946572 0.22868036 0.39948938]
  [0.15229335 0.80574522 0.05742522 0.43946237]]]


In [ ]:
print(np.argmax(L,axis=2))

[[1 2 1 2 0 1]]


print(np.argmin(L,axis=0))

In [ ]:
print(np.argmin(K,axis=0))

[1 5 4 0]


In [ ]:
print(np.argmin(K,axis=1))

[3 0 3 3 2 2]


Searching

In [ ]:
M=np.array([34,56,7,17,88,91])
print(np.where(M%2==0))

(array([0, 1, 4]),)


In [ ]:
N=np.random.rand(6)
print(N)

[0.08214699 0.19862873 0.33604818 0.38512437 0.88798855 0.44715919]


In [ ]:
print(np.where(N%2==0))

(array([], dtype=int64),)


In [ ]:
O=np.array([24,16,7,17,54,60])
print(np.where(O%6==0))

(array([0, 4, 5]),)


In [ ]:
P=np.array([2,3,4,5])
print(np.searchsorted(P,1))   #searchsorted is used to find position of given sorted array name and given element

0


Sorting


In [ ]:
Q=np.sort(([2,4,3]))
print(Q)

[2 3 4]


In [ ]:
R=np.sort(([2,5,4],[9,5,2]))
print(R)

[[2 4 5]
 [2 5 9]]


Array filtering

In [ ]:
S=np.sort([1,2,3,4])
T=[True,False,True,False]
U=S[T]
print(U)


[1 3]


In [ ]:
V=np.array([2,3,4,5])
W=np.array([22,33,44,55])
print(W[np.where(V%2==0)])

[22 44]


Zip()



In [ ]:
X=np.array(["lokesh","kiran","krishna"])
Y=np.array(["gl","ck","sk"])
for i,j in zip(X,Y):
  print(i,"short name is ",j)

lokesh short name is  gl
kiran short name is  ck
krishna short name is  sk


In [ ]:
Z=np.array([2,4,6,8])
a=np.array([1,2,1,2])
print(np.mod(Z,a))      #o/p is array of remainder

[0 0 0 0]


In [ ]:
print(np.divide(Z,a)) #o/p is array of quotient


[2. 2. 6. 4.]


In [ ]:
print(np.divmod(Z,a))  #in the o/p it gives array of quotient and array of remainder

(array([2, 2, 6, 4]), array([0, 0, 0, 0]))


In [ ]:
print(np.multiply(Z,a))

[ 2  8  6 16]


logarithms

In [ ]:
b=np.arange(1,10)
print(np.log10(b))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
print(np.log(b))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
print(np.log2(b))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
c=np.array([1,2,3])
for i in c:
  print(np.log,i,(i))

<ufunc 'log'> 1 1
<ufunc 'log'> 2 2
<ufunc 'log'> 3 3


cummilative product

In [ ]:
d=np.array([1,2,3,4])
print(np.cumprod(d))

[ 1  2  6 24]


In [ ]:
print(np.diff(d))      #second element -first element

[1 1 1]


In [ ]:
print(np.lcm(3,4))

12


In [ ]:
print(np.gcd(3,6))

3


In [ ]:
print(np.cumsum(d))  #first elemet + second element

[ 1  3  6 10]


In [ ]:
#for array we use "reduce"
e=np.array([12,34,56])
print(np.gcd.reduce(e))

2


In [ ]:
print(np.lcm.reduce(e))

2856
